# Eureka Server Configuration
spring:
#  profiles: local
  application:
     name: frog-eureka-service
server:
  port: 18761
eureka:
  environment: local
  instance:
    hostname: localhost
  client:
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false