#spring properties
spring:
  application:
    name: frog-charge-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cdot_elec_frog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: chargedot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 2
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    logSlowSql: true
    maxWait: 30000
  #kafka config
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: frogChargeService
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #redis config
  redis:
    host: 127.0.0.1
    port: 6379

#eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    filter-only-up-instances: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    fetch-registry: true

#server config
server:
  port: 8553

#restTemplate time out config
rest:
  connectionRequestTimeout: 35000
  readTimeout: 35000
  connectTimeout: 35000

#url config
config:
  url: https://minipro.elefrog.com:2443/

#mybatis config
mybatis:
  mapper-locations: classpath:com/chargedot/charge/mapper/*.xml
  type-aliases-package: com.chargedot.charge.model

#logging config
logging:
  level:
    com.chargedot.elecfrogservice.dao.mapper: debug

#hystrix time out config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000